import { Router } from "express";
import { AnalysisResultSchema, UserIntentSchema } from "@autovio/shared";
import type { AnalysisResult, ScenarioScene, StyleGuide, UserIntent, AssetUsageMode, ProjectAsset } from "@autovio/shared";
import { ScenarioSceneSchema } from "@autovio/shared";
import { isStyleGuideEmpty } from "@autovio/shared";
import { z } from "zod";
import { getLLMProvider } from "../providers/registry.js";
import {
  getScenarioSystemPrompt,
  getScenarioUserPrompt,
  formatStyleGuideForPrompt,
} from "../prompts/scenario.js";
import { authenticate, requireScope } from "../middleware/auth.js";
import { buildAssetReferenceContext } from "../utils/asset-integration.js";

const router = Router();

router.use(authenticate);

/** Shared scenario generation: same logic as UI "Build Scenario". Used by POST /api/scenario and POST /api/projects/:projectId/works/:workId/scenario. */
export async function generateScenario(
  analysis: AnalysisResult | null | undefined,
  intent: UserIntent,
  options: {
    systemPrompt?: string;
    knowledge?: string;
    styleGuide?: StyleGuide;
    selectedAssets?: ProjectAsset[];
    assetUsageMode?: AssetUsageMode;
  },
  apiKey: string,
  providerId: string = "gemini",
  modelId?: string
): Promise<ScenarioScene[]> {
  const provider = getLLMProvider(providerId);
  let baseSystemPrompt = options.systemPrompt?.trim() || getScenarioSystemPrompt();
  if (options.styleGuide && !isStyleGuideEmpty(options.styleGuide)) {
    baseSystemPrompt += "\n\n" + formatStyleGuideForPrompt(options.styleGuide);
  }
  
  // Add asset context based on mode
  if (options.selectedAssets && options.selectedAssets.length > 0) {
    if (options.assetUsageMode === "reference") {
      // REFERENCE mode: Add descriptions for AI to learn style
      const assetContext = buildAssetReferenceContext(options.selectedAssets);
      if (assetContext) {
        baseSystemPrompt += assetContext;
      }
    } else if (options.assetUsageMode === "direct") {
      // DIRECT mode: Inform LLM that specific images will be used
      baseSystemPrompt += `\n\n## Direct Asset Mode
User has provided ${options.selectedAssets.length} specific image(s) to use directly in the video.
Create exactly ${options.selectedAssets.length} scene(s), one for each provided image.
Each scene's image_prompt should describe how to present or animate that specific asset (camera movement, transitions, etc.).
The images are already provided and will NOT be generated by AI - focus on describing the motion and presentation.

Assets available:
${options.selectedAssets.map((a, i) => `${i + 1}. ${a.name}${a.description ? `: ${a.description}` : ""}`).join("\n")}`;
    }
  }
  
  const systemPrompt = options.knowledge?.trim()
    ? `${baseSystemPrompt}\n\n## Project information (to understand this project)\n${options.knowledge.trim()}`
    : baseSystemPrompt;
  const userPrompt = getScenarioUserPrompt(analysis ?? undefined, intent);

  console.log(`[scenario] provider=${providerId} model=${modelId}`);
  const response = await provider.generate(systemPrompt, userPrompt, apiKey, modelId);
  const jsonMatch = response.match(/```json\s*([\s\S]*?)```/) || response.match(/\[[\s\S]*\]/);
  if (!jsonMatch) {
    console.error("❌ [SCENARIO] Failed to extract JSON from response:", response.substring(0, 500));
    throw new Error("Failed to parse scenario response as JSON");
  }
  const jsonString = jsonMatch[1] || jsonMatch[0];
  console.log("🔍 [SCENARIO] Extracted JSON string:", jsonString.substring(0, 500));
  
  let raw;
  try {
    raw = JSON.parse(jsonString);
  } catch (parseError) {
    console.error("❌ [SCENARIO] JSON parse error:", parseError);
    console.error("❌ [SCENARIO] Full JSON string:", jsonString);
    throw new Error(`Failed to parse LLM response as valid JSON: ${parseError instanceof Error ? parseError.message : String(parseError)}`);
  }
  
  return z.array(ScenarioSceneSchema).parse(raw);
}

const RequestSchema = z.object({
  analysis: AnalysisResultSchema.optional(),
  intent: UserIntentSchema,
  systemPrompt: z.string().optional(),
  knowledge: z.string().optional(),
  styleGuide: z
    .object({
      tone: z.string().optional(),
      color_palette: z.array(z.string()).optional(),
      tempo: z.enum(["fast", "medium", "slow"]).optional(),
      camera_style: z.string().optional(),
      brand_voice: z.string().optional(),
      must_include: z.array(z.string()).optional(),
      must_avoid: z.array(z.string()).optional(),
    })
    .optional(),
});

router.post("/", requireScope("ai:generate"), async (req, res, next) => {
  try {
    const providerId = (req.headers["x-llm-provider"] as string) || "gemini";
    const modelId = req.headers["x-model-id"] as string | undefined;
    const apiKey = req.headers["x-api-key"] as string;

    if (!apiKey) {
      res.status(400).json({ error: "API key required (x-api-key header)" });
      return;
    }

    const {
      analysis,
      intent,
      systemPrompt: customSystemPrompt,
      knowledge,
      styleGuide,
    } = RequestSchema.parse(req.body);
    const scenes = await generateScenario(
      analysis ?? null,
      intent,
      { systemPrompt: customSystemPrompt, knowledge, styleGuide },
      apiKey,
      providerId,
      modelId
    );
    res.json({ scenes });
  } catch (err) {
    next(err);
  }
});

export default router;
